[general]
import = [
    # "~/.config/alacritty/themes/vscode.toml"
]

[terminal.shell]
program = "/bin/zsh"
args = [ "-l", "-c", "tmux a || tmux" ]

[font]
# ueoai this line is used for comparing line height
# iaoeu this line is used for comparing line height
size = 16
normal = { family = "Monaspace Argon NF", style = "Regular" }
bold = { family = "Monaspace Argon NF", style = "Bold" }
offset = { x = -1, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[window]
dynamic_padding = true
decorations = "Buttonless"
opacity = 1
blur = true
padding = { x = 16, y = 16 }
dimensions = { columns = 120, lines = 40 }
startup_mode = "Maximized"

[cursor]
style = { shape = "Block", blinking = "On" }

[mouse]
hide_when_typing = true

[env]
# TERM = "xterm-256color"
WAYLAND_DISPLAY= "alacritty"

[colors]
primary.background = '#1C1C1C'
normal.black = '#1C1C1C'

[keyboard]
bindings = [
  { key = "Key6", mods = "Control", chars = "\u001e" }
]
